<?php

namespace App\Enums;

enum UnitEventType: string
{
    case UNIT_IMPORTED = 'UNIT_IMPORTED';

    case ARRIVAL_STARTED = 'ARRIVAL_STARTED';
    case ARRIVAL_COMPLETED = 'ARRIVAL_COMPLETED';

    case ASSEMBLY_STARTED = 'ASSEMBLY_STARTED';
    case ASSEMBLY_COMPLETED = 'ASSEMBLY_COMPLETED';

    case DELIVERY_STARTED = 'DELIVERY_STARTED';
    case DELIVERY_COMPLETED = 'DELIVERY_COMPLETED';

    case EVIDENCE_ADDED = 'EVIDENCE_ADDED';
    case EVIDENCE_REMOVED = 'EVIDENCE_REMOVED';
}
